# Generated by Django 4.2.6 on 2023-11-25 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("hash_id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="uploads/")),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.TextField(max_length=200, primary_key=True, serialize=False),
                ),
                (
                    "file_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="picnix_backbone.image",
                    ),
                ),
            ],
        ),
    ]
