# Generated by Django 4.2.6 on 2023-12-03 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("picnix_backbone", "0003_alter_post_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="image_id",
            new_name="image",
        ),
    ]
