# Generated by Django 4.2.7 on 2023-12-03 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picnix_backbone', '0004_rename_image_id_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterInfo',
            fields=[
                ('cluster_number', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('cluster_center', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageCluster',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('cluster', models.IntegerField()),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picnix_backbone.image')),
            ],
        ),
    ]
