# Generated by Django 4.2.7 on 2023-12-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picnix_backbone', '0006_alter_imagecluster_image_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clusterinfo',
            old_name='cluster_number',
            new_name='cluster_id',
        ),
        migrations.RenameField(
            model_name='imagecluster',
            old_name='cluster',
            new_name='cluster_id',
        ),
        migrations.AlterField(
            model_name='imagecluster',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imagecluster',
            name='image_id',
            field=models.IntegerField(),
        ),
    ]
