# Generated by Django 4.2.7 on 2023-12-04 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picnix_backbone', '0007_rename_cluster_number_clusterinfo_cluster_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClusterInfo',
        ),
    ]
