# Generated by Django 4.2.7 on 2023-12-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picnix_backbone', '0008_delete_clusterinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cluster_id', models.IntegerField()),
                ('cluster_center', models.TextField()),
            ],
        ),
    ]
