# Generated by Django 4.2.6 on 2023-12-04 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("picnix_backbone", "0009_clusterinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="num_refs",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="imagecluster",
            unique_together={("image_id", "cluster_id")},
        ),
    ]
